config/routes.rb
Rails.application.routes.draw do
  root 'departments#index'
  
  resources :departments do
    resources :items
  end

  scope 'items/:item_id', as: 'item' do
    resources :testimonials, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :department
  has_many :testimonials
end

app/models/testimonial.rb
class Testimonial < ApplicationRecord
  belongs_to :item
  before_save :check_author

  def check_author
    if self.author.blank?
      self.author = 'Guest'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]
  
  def index
    @departments = Department.all
  end

  def show
  end

  def new
    @department = Department.new
    render :form
  end

  def edit
    render :form
  end

  def update
    if @department.update(department_params)
      redirect_to @department
    else
      render :form
    end
  end

  def create
    @department = Department.new(department_params)
    if @department.save
      redirect_to departments_path
    else
      render :form
    end
  end

  def destroy
    @department.destroy
    redirect_to departments_path
  end

  private

    def department_params
      params.require(:department).permit(:name)
    end

    def set_department
      @department = Department.find(params[:id])
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_department
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  
  def index
    @items = @department.items
  end

  def show
  end

  def new
    @item = Item.new
    render :form
  end

  def edit
    render :form
  end

  def create
    @item = @department.items.new(item_params)
    if @item.save
      redirect_to [@department, @item]
    else
      render :form
    end
  end

  def update
    if @item.update(item_params)
      redirect_to [@department, @item]
    else
      render :form
    end
  end

  def destroy
  end

  private
    def item_params
      params.require(:item).permit(:name, :price)
    end

    def set_department
      @department = Department.find(params[:department_id])
    end

    def set_item
      @item = Item.find(params[:id])
    end
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  before_action :set_item
  
  def new
    @testimonial = Testimonial.new
  end

  def create
    @testimonial = @item.testimonials.new(testimonial_params)
    if @testimonial.save
      redirect_to department_item_path(@item.department_id, @item)
    else
      render :new
    end
  end

  private
    def set_item
      @item = Item.find(params[:item_id])
    end

    def testimonial_params
      params.require(:testimonial).permit(:desc, :author)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/views/departments/form.html.erb
<h1><%= @department.id ? "Edit Department" : "Create Department" %></h1>
<%= form_for @department do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/departments/index.html.erb
<h1>Welcome to the Murder Store departments list</h1>
<%= link_to 'Create a new Department', new_department_path %>
<hr />
<div class="d_wrapper">
  <% @departments.each do |department| %>
  <%= link_to department.name, department %>
<% end %>
</div>
<hr />

app/views/departments/show.html.erb
<h1>Details of department: <strong><%= @department.name %></strong></h1>
<hr />
<p>Name: <%= @department.name %>
<br />
<%= link_to 'Show Murder Options', department_items_path(@department) %>
<br />
<%= link_to 'Edit Department', edit_department_path(@department) %>
<br />
<%= link_to 'Delete Department', @department, method: :delete %></p>
<hr />

app/views/items/form.html.erb
<h1><%= @item.id ? "Edit Item" : "Create Item" %></h1>
<%= form_for [@department, @item] do |f| %>
<%= f.label :name %>
<%= f.text_field :name, required: true, autofocus: true %>
<br />
<%= f.label :price %>
<%= f.text_field :price, required: true %>
<%= f.submit %>
<% end %>

app/views/items/index.html.erb
<h1><%= @department.name %> Options</h1>
<hr />
<%= link_to 'Create a new Murder Option', new_department_item_path(@department) %>
<div class="d_wrapper">
<% @items.each do |item| %>
  <%= link_to item.name, [@department, item] %>
<% end %>
</div>

app/views/items/show.html.erb
<h1>Department: <i><%= @department.name %></i>, Option: <i><%= @item.name %></i></h1>
<hr />
<p>With this option, you will be murdered in <strong><%= @department.name %></strong> by <strong><%= @item.name %></strong> for only <strong>$<%= @item.price %>!</strong></p>
<h2>Testimonials</h2>
<% @item.testimonials.each do |testimonial| %>
<%= render 'testimonials/testimonial', { testimonial: testimonial } %>
<% end %>
<%= link_to 'Add Testimonial', new_item_testimonial_path(@item) %>
<%= link_to 'Edit Option', edit_department_item_path([@department, @item]) %>
<%= link_to 'Delete Option', [@department, @item], method: :delete %>
<%= link_to 'Back to Options', department_items_path(@department) %>

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MurderStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', "https://fonts.googleapis.com/css?family=Gaegu" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/testimonials/_testimonial.html.erb
<hr />
<p>Author: <%= testimonial.author %></p>
<p>Testimonial: <%= testimonial.desc %></p>
<hr />

app/views/testimonials/new.html.erb
<h1>Add a Testimonial!</h1>
<%= form_for [@item, @testimonial] do |f| %>
<%= f.label :desc %>
<%= f.text_area :desc, required: true, autofocus: true %>
<br />
<%= f.label :author %>
<%= f.text_field :author, placeholder: "Guest" %>
<%= f.submit %>
<% end %>